# Generated by Django 3.2.7 on 2021-09-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(max_length=4),
        ),
    ]
