# Generated by Django 3.2.7 on 2021-09-29 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0003_auto_20210928_1956'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airline',
            table='airline',
        ),
        migrations.AlterModelTable(
            name='credit_card',
            table='credit_card',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='flight',
            table='flight',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
