# Generated by Django 3.2.7 on 2021-09-29 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0004_auto_20210928_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='flytofasto_api.customer'),
        ),
    ]
