# Generated by Django 3.2.7 on 2021-09-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0005_alter_ticket_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
