# Generated by Django 3.2.7 on 2021-10-05 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0006_auto_20210928_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='flytofasto_api.country')),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('province', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, to='flytofasto_api.province')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.AlterField(
            model_name='flight',
            name='location_from',
            field=models.ForeignKey(db_column='location_id_from', on_delete=django.db.models.deletion.CASCADE, related_name='location_id_from', to='flytofasto_api.city'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='location_to',
            field=models.ForeignKey(db_column='location_id_to', on_delete=django.db.models.deletion.CASCADE, related_name='location_id_to', to='flytofasto_api.city'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
