# Generated by Django 3.2.7 on 2021-11-04 05:24

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0007_auto_20211005_1824'),
    ]

    operations = [
        migrations.RenameField('Flight', 'location_to', 'arrival_city'),
        migrations.RenameField('Flight', 'location_from', 'departure_city'),
    ]
