# Generated by Django 3.2.7 on 2021-11-04 05:39

from django.db import migrations
import os

from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'initial_data.json'

def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file) 

def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    MyModel = apps.get_model("flytofasto_api", "ModelName")
    MyModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0009_auto_20211104_0535'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
