# Generated by Django 3.2.7 on 2021-11-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0010_auto_20211104_0539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credit_card',
            new_name='CreditCard',
        ),
    ]
