# Generated by Django 3.2.7 on 2021-11-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0011_rename_credit_card_creditcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id']},
        ),
    ]
