# Generated by Django 3.2.7 on 2021-11-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flytofasto_api', '0012_auto_20211122_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
